#!/usr/bin/env bash
# This script configures localhost and facebook.com IP resolutions

# Backup the current /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Add the new configurations to /etc/hosts
sudo sed -i '/localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
